apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-deploy111
  namespace: argocd
  labels:
    app: argo1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo1
  template:
    metadata:
      labels:
        app: argo1
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: argo-pod
        image: mohnishbhonde/sns01
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
